"""
Django settings for bachata_buddy project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-+fmq=zy&$!pdc-*qb#1rqy2x!$ff0=8lo6otp&zy$o6$s1jk(3')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

# ALLOWED_HOSTS configuration for production
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# CSRF trusted origins for Cloud Run
CSRF_TRUSTED_ORIGINS = [
    f'https://{host}' for host in ALLOWED_HOSTS 
    if host not in ['localhost', '127.0.0.1']
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps
    'django_htmx',
    # Local apps
    'core',  # Shared services and utilities
    'users',
    'choreography',
    'user_collections',
    'instructors',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Serve static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
]

ROOT_URLCONF = 'bachata_buddy.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
            ],
        },
    },
]

WSGI_APPLICATION = 'bachata_buddy.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Check if running on Cloud Run with Cloud SQL Unix socket
if os.environ.get('CLOUD_SQL_CONNECTION_NAME') and os.environ.get('ENVIRONMENT') == 'cloud':
    # Use Unix socket for Cloud SQL connection (Cloud Run)
    # Cloud Run mounts the socket at /cloudsql/<connection-name>
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'bachata-buddy'),
            'USER': os.environ.get('DB_USER', 'postgres'),
            'PASSWORD': os.environ.get('DB_PASSWORD', ''),
            'HOST': '/cloudsql/' + os.environ.get('CLOUD_SQL_CONNECTION_NAME'),
            'ATOMIC_REQUESTS': False,
        }
    }
else:
    # Use TCP/IP for local development, Compute Engine, or external connections
    # For Compute Engine: Set DB_HOST to Cloud SQL private IP or public IP
    # For local dev: Set DB_HOST to localhost or 127.0.0.1
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'bachata_vibes'),
            'USER': os.environ.get('DB_USER', 'postgres'),
            'PASSWORD': os.environ.get('DB_PASSWORD', ''),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '5432'),
            'ATOMIC_REQUESTS': False,
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 6,
        }
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Whitenoise configuration for serving static files in production
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files configuration
# Supports both local development and Google Cloud Storage in production

# Check if running in cloud environment with GCS bucket configured
USE_GCS = os.environ.get('GCS_BUCKET_NAME') and os.environ.get('ENVIRONMENT') == 'cloud'

if USE_GCS:
    # Google Cloud Storage configuration for production
    GS_BUCKET_NAME = os.environ.get('GCS_BUCKET_NAME')
    GS_PROJECT_ID = os.environ.get('GCP_PROJECT_ID')
    GS_DEFAULT_ACL = 'publicRead'  # Make videos publicly accessible
    GS_FILE_OVERWRITE = False  # Don't overwrite files with same name
    GS_LOCATION = 'media'  # Folder within bucket
    
    # Use GCS for media files
    DEFAULT_FILE_STORAGE = 'storages.backends.gcs.GSGoogleCloudStorage'
    MEDIA_URL = f'https://storage.googleapis.com/{GS_BUCKET_NAME}/media/'
    
    # For local temp files during processing (Cloud Run has /tmp)
    TEMP_ROOT = '/tmp'
else:
    # Local development configuration
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'data'
    TEMP_ROOT = BASE_DIR / 'data' / 'temp'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication settings
LOGIN_URL = 'users:login'
LOGIN_REDIRECT_URL = 'choreography:index'
LOGOUT_REDIRECT_URL = 'choreography:index'

# Custom user model
AUTH_USER_MODEL = 'users.User'
