# Generated by Django 5.2.7 on 2025-11-01 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoreographyTask',
            fields=[
                ('task_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('started', 'Started'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='started', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('stage', models.CharField(default='initializing', max_length=50)),
                ('message', models.TextField(default='Starting choreography generation...')),
                ('result', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('job_execution_name', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choreography_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Choreography Task',
                'verbose_name_plural': 'Choreography Tasks',
                'db_table': 'choreography_tasks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='choreograph_user_id_1f71cb_idx'), models.Index(fields=['created_at'], name='choreograph_created_1c4810_idx')],
            },
        ),
    ]
