# Generated by Django 5.2.7 on 2025-11-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choreography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('artist', models.CharField(db_index=True, max_length=200)),
                ('duration', models.FloatField(help_text='Duration in seconds')),
                ('bpm', models.IntegerField(blank=True, help_text='Beats per minute', null=True)),
                ('genre', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('audio_path', models.CharField(help_text='Local path (songs/file.mp3) or GCS path (gs://bucket/songs/file.mp3)', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Song',
                'verbose_name_plural': 'Songs',
                'db_table': 'songs',
                'ordering': ['title'],
                'indexes': [models.Index(fields=['title'], name='songs_title_82952e_idx'), models.Index(fields=['artist'], name='songs_artist_e25abe_idx'), models.Index(fields=['genre'], name='songs_genre_a4b7c8_idx')],
            },
        ),
    ]
