# Generated by Django 5.2.7 on 2025-11-08 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choreography', '0002_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='choreographytask',
            name='song',
            field=models.ForeignKey(blank=True, help_text='Song template used for generation (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='choreography.song'),
        ),
    ]
