# Generated by Django 5.2.7 on 2025-11-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choreography', '0003_choreographytask_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoveEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('move_name', models.CharField(db_index=True, max_length=200)),
                ('video_path', models.CharField(help_text='Path to video file (local or GCS)', max_length=500)),
                ('pose_embedding', models.JSONField(help_text='512D pose embedding vector')),
                ('audio_embedding', models.JSONField(help_text='128D audio embedding vector')),
                ('text_embedding', models.JSONField(help_text='384D text embedding vector')),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], db_index=True, max_length=20)),
                ('energy_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, max_length=20)),
                ('style', models.CharField(choices=[('romantic', 'Romantic'), ('energetic', 'Energetic'), ('sensual', 'Sensual'), ('playful', 'Playful')], db_index=True, max_length=50)),
                ('duration', models.FloatField(help_text='Duration in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Move Embedding',
                'verbose_name_plural': 'Move Embeddings',
                'db_table': 'move_embeddings',
                'ordering': ['move_name'],
                'indexes': [models.Index(fields=['move_id'], name='move_embedd_move_id_0a7382_idx'), models.Index(fields=['difficulty', 'energy_level', 'style'], name='move_embedd_difficu_699cb8_idx')],
            },
        ),
    ]
