# Generated by Django 5.2.7 on 2025-11-09 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choreography', '0004_moveembedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blueprint',
            fields=[
                ('task', models.OneToOneField(help_text='The choreography task this blueprint belongs to', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='blueprint', serialize=False, to='choreography.choreographytask')),
                ('blueprint_json', models.JSONField(help_text='Complete blueprint specification including moves, timing, and output config')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blueprint',
                'verbose_name_plural': 'Blueprints',
                'db_table': 'blueprints',
                'ordering': ['-created_at'],
            },
        ),
    ]
