# Generated by Django 5.2.7 on 2025-12-05 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choreography', '0005_blueprint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choreographytask',
            name='job_execution_name',
        ),
    ]
