# Generated by Django 5.2.7 on 2025-11-01 14:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedChoreography',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('video_path', models.FileField(max_length=500, upload_to='choreographies/%Y/%m/')),
                ('thumbnail_path', models.ImageField(blank=True, max_length=500, null=True, upload_to='thumbnails/%Y/%m/')),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], db_index=True, max_length=20)),
                ('duration', models.FloatField(help_text='Duration in seconds')),
                ('music_info', models.JSONField(blank=True, null=True)),
                ('generation_parameters', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choreographies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Choreography',
                'verbose_name_plural': 'Saved Choreographies',
                'db_table': 'saved_choreographies',
                'ordering': ['-created_at'],
            },
        ),
    ]
