# Generated by Django 5.2.7 on 2025-10-12 18:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], db_index=True, max_length=20)),
                ('estimated_duration', models.IntegerField(blank=True, help_text='Estimated duration in minutes', null=True)),
                ('instructor_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Class Plan',
                'verbose_name_plural': 'Class Plans',
                'db_table': 'class_plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassPlanSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence_order', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('estimated_time', models.IntegerField(blank=True, help_text='Estimated time for this sequence in minutes', null=True)),
            ],
            options={
                'verbose_name': 'Class Plan Sequence',
                'verbose_name_plural': 'Class Plan Sequences',
                'db_table': 'class_plan_sequences',
                'ordering': ['sequence_order'],
            },
        ),
    ]
