# Generated by Django 5.2.7 on 2025-10-12 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('choreography', '0002_initial'),
        ('instructors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classplan',
            name='instructor',
            field=models.ForeignKey(limit_choices_to={'is_instructor': True}, on_delete=django.db.models.deletion.CASCADE, related_name='class_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classplansequence',
            name='choreography',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_sequences', to='choreography.savedchoreography'),
        ),
        migrations.AddField(
            model_name='classplansequence',
            name='class_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='instructors.classplan'),
        ),
        migrations.AlterUniqueTogether(
            name='classplansequence',
            unique_together={('class_plan', 'sequence_order')},
        ),
    ]
