"""Initial migration: create users, saved_choreographies, class_plans, and class_plan_sequences tables

Revision ID: 06302da80e06
Revises: 
Create Date: 2025-09-27 16:28:24.204088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06302da80e06'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('is_instructor', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('class_plans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('instructor_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('difficulty_level', sa.String(), nullable=False),
    sa.Column('estimated_duration', sa.Integer(), nullable=True),
    sa.Column('instructor_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_class_plans_created_at'), 'class_plans', ['created_at'], unique=False)
    op.create_index(op.f('ix_class_plans_instructor_id'), 'class_plans', ['instructor_id'], unique=False)
    op.create_table('saved_choreographies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('video_path', sa.String(), nullable=False),
    sa.Column('thumbnail_path', sa.String(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('music_info', sa.JSON(), nullable=True),
    sa.Column('generation_parameters', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_choreographies_created_at'), 'saved_choreographies', ['created_at'], unique=False)
    op.create_index(op.f('ix_saved_choreographies_user_id'), 'saved_choreographies', ['user_id'], unique=False)
    op.create_table('class_plan_sequences',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('class_plan_id', sa.String(), nullable=False),
    sa.Column('choreography_id', sa.String(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('estimated_time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['choreography_id'], ['saved_choreographies.id'], ),
    sa.ForeignKeyConstraint(['class_plan_id'], ['class_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_class_plan_sequences_class_plan_id'), 'class_plan_sequences', ['class_plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_class_plan_sequences_class_plan_id'), table_name='class_plan_sequences')
    op.drop_table('class_plan_sequences')
    op.drop_index(op.f('ix_saved_choreographies_user_id'), table_name='saved_choreographies')
    op.drop_index(op.f('ix_saved_choreographies_created_at'), table_name='saved_choreographies')
    op.drop_table('saved_choreographies')
    op.drop_index(op.f('ix_class_plans_instructor_id'), table_name='class_plans')
    op.drop_index(op.f('ix_class_plans_created_at'), table_name='class_plans')
    op.drop_table('class_plans')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
