"""Add user preferences for auto-save

Revision ID: 54c109daf8f1
Revises: 06302da80e06
Create Date: 2025-09-27 21:46:28.328422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54c109daf8f1'
down_revision: Union[str, None] = '06302da80e06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add column as nullable first (SQLite limitation)
    op.add_column('users', sa.Column('preferences', sa.JSON(), nullable=True))
    
    # Update existing users with default preferences
    connection = op.get_bind()
    connection.execute(
        sa.text("UPDATE users SET preferences = :default_prefs WHERE preferences IS NULL"),
        {"default_prefs": '{"auto_save_choreographies": true}'}
    )
    
    # Note: SQLite doesn't support altering column to NOT NULL, so we leave it nullable
    # The application code will handle the default value


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferences')
    # ### end Alembic commands ###
